---
title: "Bar Race Chart Medalhas"
author: "ABC - Estatística"
Date: 22/07/2021
output:
  rmdformats::material:
  highlight: kate
---
# Carregando pacotes
```{r,message=FALSE}
library(readxl)
library(tidyverse)
library(janitor)
library(gganimate)
library(gifski)
library(av)
library(Rcpp)
```

# Carregando os dados
```{r}
url <- "https://drive.google.com/uc?export=download&id=19BsfjmeuYSWbSvmb_NrGtMIOqdCsfWEa"
base <- read.csv(url)
```
# Arrumando os dados
```{r}
base_clean <- base %>%
  janitor::clean_names() %>%      # coloca em minúscula, tira acentos
  mutate(ano = as.numeric(ano))   # altera o formato da coluna ano para numeric
```
# Arrumando tabela
```{r}
tabela <- base_clean %>%
  group_by(ano) %>%                 # agrupa por ano
  mutate(rank = rank(-valor)) %>%   # cria a variável rank
  group_by(pais) %>%                # agrupa por país
  filter(rank <= 10)                # seleciona os 10 maiores valores do rank
  #ungroup()                         # desagrupa
```
# Fazendo gráfico estáticos
```{r,warning=FALSE}
staticplot = ggplot(tabela, aes(rank, group = pais,
                                       fill = as.factor(pais), 
                                       color = as.factor(pais))) +
  geom_tile(aes(y = valor/2,
                height = valor,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(pais, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=valor,label = valor, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=1, color="grey" ),
        panel.grid.minor.x = element_line( size=1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
        plot.margin = margin(2,2, 2, 4, "cm"))
```

# Criando gráfico animado a partir dos estáticos
```{r,warning=FALSE}
# Animação
anim = staticplot + transition_states(ano, transition_length = 5, state_length = 10) +
  view_follow(fixed_x = TRUE)  +
  labs(title = 'Ano: {closest_state}',
       subtitle  =  "Top 10 Países",
       caption  = "Medalhas Olímpicas/país")

# GIF
animate(plot = anim, nframes = 28, fps = 5,  width = 600, height = 800,
        renderer = gifski_renderer("race.gif"))
```
